services:
  # Backend Service
  - type: web
    name: quiz-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        sync: false
    healthCheckPath: /api/session/health

  # Frontend Service (opsiyonel - Vercel kullan覺yorsan覺z bu k覺sm覺 silin)
  # - type: web
  #   name: quiz-frontend
  #   runtime: static
  #   buildCommand: cd client && npm install && npm run build
  #   staticPublishPath: ./client/dist

